CREATE TABLE IF NOT EXISTS admins (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 999 INCREMENT BY 1000),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(155) UNIQUE NOT NULL,
  password VARCHAR(500) NOT NULL,
  firstname VARCHAR(60) NOT NULL,
  lastname VARCHAR(60) NOT NULL,
  phonenumber VARCHAR(20) UNIQUE NOT NULL,
  nationalcode VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP NULL
);